# Generated by Django 5.1.1 on 2024-10-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_students_branch_alter_students_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('emp_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
